name: Build and deploy
on:
  push:
    branches:
      - master

env:
  SHA: ${{ github.sha }}

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: '270.0.0'
          service_account_email: ${{ secrets.GKE_EMAIL }}
          service_account_key: ${{ secrets.GKE_KEY }}

      - name: Config GCloud
        run: |
          gcloud config set project multi-k8s-262117
          gcloud config set compute/zone europe-north1-a
          gcloud container clusters get-credentials multi-cluster

      - name: Login to Docker
        run: docker login --username ${{ secrets.DOCKER_USERNAME }} --password ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and test client
        run: |
          docker build -t lazycoder/react-test -f ./client/Dockerfile.dev ./client
          docker run lazycoder/react-test yarn test --coverage

      - name: Deploy
        run: ./deploy.sh
